[project]
name = "data-pipeline"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "shared",
    "boto3[s3]>=1.43.95",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "pymupdf>=1.28.2",
]


[tool.uv.sources]
shared = { workspace = true }

[tool.ruff]
lint.ignore=["PTH"]

[dependency-groups]
dev = [
    "arabic-reshaper>=3.0.1",
    "python-bidi>=0.6.11",
]
